# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
project: StreetComplete
title: StreetComplete
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # GitHub sets this to streetcomplete-website/ so relative links work
url: "https://rugk.github.io" # for now

# Build settings
markdown: kramdown
jsend: '.js' # prod: .min.js
safe: true
timezone: Europe/Berlin
encoding: utf-8

# snippets
externalmdlink: '{:target="_blank"}{:rel="noopener noreferrer"}' # for external links

sass:
#  style: compressed # for production
  sass_dir: assets/_sass

# # do compress:
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   ignore:
#     envs: []
#   blanklines: false

# NOT compress
compress_html:
  clippings: all
  comments: ["<!--X ", " -->"]
  ignore:
    envs: ['developmentX'] # "disabled", because you may want to use blanklines
  blanklines: true

# Exclude stuff
exclude:
- CONTRIBUTING.md
- LICENSE.md
- README.md
