project: StreetComplete
title: StreetComplete
# email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # GitHub sets this to streetcomplete-website/ so relative links work
url: "https://rugk.github.io" # for now

# Build settings
markdown: kramdown
jsend: '.js' # prod: .min.js
safe: true
timezone: Europe/Berlin
encoding: utf-8

# snippets
externalmdlink: '{:target="_blank"}{:rel="noopener noreferrer"}' # for external links

sass:
#  style: compressed # for production
  sass_dir: assets/_sass

# # do compress:
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   ignore:
#     envs: []
#   blanklines: false

# NOT compress
compress_html:
  clippings: all
  comments: ["<!--X ", " -->"]
  ignore:
    envs: ['developmentX'] # "disabled", because you may want to use blanklines
  blanklines: true

# Exclude stuff
exclude:
- CONTRIBUTING.md
- LICENSE.md
- README.md
